name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t devide_task .

      - name: Run Python lint/format/tests in Docker container
        run: |
          docker run --rm devide_task bash -c "flake8 . && black --check . && python -c \"print('Hello World')\""

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Node.js dependencies
        run: npm install
      - name: Run Node.js lint and test
        run: |
          npx eslint . || echo "ESLint check skipped if no config"
          node -e "console.log('Hello World')"
