name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          pip install flake8 black
      - name: Run Python lint and format check
        run: |
          flake8 .
          black --check .
          python -c "print('Hello World')"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Node.js dependencies
        run: |
          npm install
      - name: Run Node.js lint and test
        run: |
          npx eslint . || echo "ESLint check skipped if no config"
          node -e "console.log('Hello World')"
